# Generated by Django 3.1.2 on 2020-10-24 01:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico_duv', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=200, null=True)),
                ('url_arq', models.URLField()),
                ('status_duv', models.CharField(choices=[('Abe', 'Em aberto'), ('Enc', 'Encerrada')], default='Abe', max_length=3)),
                ('data_duv', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ev', models.CharField(max_length=200)),
                ('descr_ev', models.CharField(max_length=200, null=True)),
                ('data_ev', models.DateTimeField()),
                ('tipo_ev', models.CharField(choices=[('Ves', 'Vestibular'), ('Sim', 'Simulado'), ('Out', 'Outros')], default='Sim', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mat', models.CharField(max_length=200)),
                ('descr_mat', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.eventos')),
                ('url_sim', models.URLField()),
                ('status_sim', models.CharField(choices=[('Pro', 'Em progresso'), ('Enc', 'Encerrado')], default='Pro', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, null=True)),
                ('url_arq', models.URLField()),
                ('data_duv', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id_duvida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.duvida')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico_mas', models.CharField(max_length=200)),
                ('descr_mas', models.CharField(max_length=200, null=True)),
                ('data_mas', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo_materiais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_arq', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('id_materiais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.materiais')),
            ],
        ),
        migrations.CreateModel(
            name='Nota_simulados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.simulado')),
            ],
        ),
    ]
