# Generated by Django 3.1.2 on 2020-10-29 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_auto_20201025_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvida',
            name='texto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='url_arq',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descr_ev',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='descr_mat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materiais',
            name='descr_mas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='texto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='url_arq',
            field=models.URLField(blank=True, null=True),
        ),
    ]
