# Generated by Django 3.1.2 on 2020-10-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_materiais_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo_materiais',
            name='nome_arq',
            field=models.CharField(default='teste', max_length=200),
        ),
        migrations.AlterField(
            model_name='arquivo_materiais',
            name='file_mat',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='file_res',
            field=models.FileField(blank=True, null=True, upload_to='duvidas/'),
        ),
    ]
