# Generated by Django 3.1.2 on 2020-11-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20201031_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo_materiais',
            name='file_mat',
            field=models.FileField(default='', upload_to='materiais/'),
        ),
        migrations.AlterField(
            model_name='arquivo_materiais',
            name='nome_arq',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
