# Generated by Django 3.1.2 on 2020-11-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20201101_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='data_ev',
            field=models.DateField(),
        ),
    ]
