# Generated by Django 3.1.2 on 2020-11-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20201104_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respostas',
            old_name='data_resp',
            new_name='data_res',
        ),
    ]
